version: '3.9'

services:

  backend_api:
    build: backend
    restart: always
    container_name: backend_api
    stop_signal: SIGINT

  frontend:
    build: frontend
    restart: always
    container_name: frontend
    stop_signal: SIGINT

  nginx:
    build: nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    stop_signal: SIGINT

  mysql:
    build: databases/mySQL
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    stop_signal: SIGINT

  phpmyadmin:
    build: databases/phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - "8080:80"
    stop_signal: SIGINT