version: '3.9'

services:

  backend_api:
    build: backend
    restart: always
    container_name: backend_api
    stop_signal: SIGINT

  frontend:
    build: frontend
    restart: always
    container_name: frontend
    stop_signal: SIGINT

  nginx:
    build: nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    stop_signal: SIGINT