FROM python:3.10

WORKDIR /src

COPY requirements.txt /src

RUN pip install --no-cache-dir -r requirements.txt

COPY . /src

ENV UVICORN_PORT 5000
ENV UVICORN_HOST 0.0.0.0
ENV UVICORN_LIFESPAN on

CMD ["uvicorn", "api:app"]